AWSTemplateFormatVersion: '2010-09-09'
Description: Projeto Pedro CloudFormation

Parameters:
  KeyName:
    Type: String
    Description: myKey

Resources:
  MainVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"

  MainGate:
    Type: AWS::EC2::InternetGateway

  GateWayConnection:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MainVPC
      InternetGatewayId: !Ref MainGate

  SubNet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MainVPC
      AvailabilityZone: us-east-1a
      CidrBlock: "10.0.0.0/24"
      MapPublicIpOnLaunch: true
  
  SubNet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MainVPC
      AvailabilityZone: us-east-1b
      CidrBlock: "10.0.2.0/24"
      MapPublicIpOnLaunch: true

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MainVPC

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: GateWayConnection
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref MainGate

  AssocSubNet1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubNet1
      RouteTableId: !Ref PublicRouteTable

  AssocSubNet2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubNet2
      RouteTableId: !Ref PublicRouteTable

  SecurityALBGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ALB
      VpcId: !Ref MainVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  MainALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: MainALB
      Subnets: 
        - !Ref SubNet1
        - !Ref SubNet2
      SecurityGroups:
        - !Ref SecurityALBGroup
      Scheme: internet-facing
      Tags:
        - Key: Name
          Value: MainALB
  
  SecurityInstancesGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: launch-wizard
      GroupDescription: launch-wizard created
      VpcId: !Ref MainVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5000
          ToPort: 5000
          CidrIp: 0.0.0.0/0

  LancConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-0e001c9271cf7f3b9
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref SecurityInstancesGroup
        - !Ref SecurityALBGroup
      IamInstanceProfile: !Ref PerfilAcessoDynamoDB
      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo apt-get update -y
          sudo apt-get install -y python3-pip git
          sudo pip3 install flask boto3
          sudo mkdir /opt/app
          sudo git clone https://github.com/PedroHrc1/AplicacaoCloud.git /opt/app
          nohup python3 /opt/app/flask_form/main.py > /var/log/main.log 2>&1 &

  ASGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones: [us-east-1a, us-east-1b]
      LaunchConfigurationName: !Ref LancConfig
      MinSize: 2
      MaxSize: 7
      DesiredCapacity: 3
      VPCZoneIdentifier:
        - !Ref SubNet1
        - !Ref SubNet2
      TargetGroupARNs:
        - !Ref GrupoAlvo  
      HealthCheckType: ELB
      HealthCheckGracePeriod: 300
      Tags:
        - Key: Name
          Value: ASGroup
          PropagateAtLaunch: true

  PoliticsEscalabity:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref ASGroup
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        TargetValue: 70.0  
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization
  
  AlarmeCPU:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Alarme de utilização da CPU excedendo 70%"
      Namespace: AWS/EC2
      MetricName: CPUUtilization
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref ASGroup
      Statistic: Average
      Period: 60
      EvaluationPeriods: 5
      Threshold: 70
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref PoliticsEscalabity

  ListenerALB:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref GrupoAlvo
      LoadBalancerArn: !Ref MainALB
      Port: 80
      Protocol: HTTP

  GrupoAlvo:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 2
      Name: GrupoAlvo
      Port: 80
      Protocol: HTTP
      TargetType: instance
      UnhealthyThresholdCount: 2
      VpcId: !Ref MainVPC

  TabelaDynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TabelaDynamoDB
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  SecGruopDynamo:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for DynamoDB
      VpcId: !Ref MainVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          SourceSecurityGroupId: !Ref SecurityInstancesGroup

  RoleAcessoDynamoDB:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DynamoDBAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:DeleteItem
                  - dynamodb:UpdateItem
                  - dynamodb:Scan
                  - dynamodb:BatchWriteItem
                  - dynamodb:BatchGetItem
                  - dynamodb:Query
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !GetAtt TabelaDynamoDB.Arn

  PerfilAcessoDynamoDB:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [!Ref RoleAcessoDynamoDB]

  VPCEndpointDynamoDB:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: com.amazonaws.us-east-1.dynamodb
      VpcId: !Ref MainVPC
      RouteTableIds:
        - !Ref PublicRouteTable
      VpcEndpointType: Gateway

Outputs:
  GrupASId:
    Description: "ID do Grupo de Auto Scaling"
    Value: !Ref ASGroup
  ALBDNSName:
    Description: "DNS Name of the ALB"
    Value: !GetAtt MainALB.DNSName
